name: Deploy container on remote
on:
  workflow_run:
    workflows: [Java CI/CD with Maven&Docker]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          script: |
            docker stop ${{ vars.REMOTE_APP_NAME }} 2>/dev/null
            docker run -d -p 80:8080 --name ${{ vars.REMOTE_APP_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
