name: Deploy container on remote
on:
  push:
    branches: [ "main" ]
    tags:
      - release_v*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            docker stop ${{ vars.REMOTE_APP_NAME }}
            docker run -d -p 8080:8080 --name ${{ vars.REMOTE_APP_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE_NAME }}:latest
